meta_product_name: "CommonsCloud"
meta_title: "community mutual aid"
meta_description: "connecting neightbours in need to those can offer support"
meta_image: "logo_filled.png" # should exist in `app/assets/images/`
